### ISSUE TITLE
드라이버 매칭된 상태에서 드라이버 호출할 수 있는 페이지로 이동가능한 이슈 

### ISSUE THREAD

**Issue by hoo00nn** [boostcamp-2020/Project09-A-Uber#141]
드라이버 매칭된 상태에서 드라이버 호출할 수 있는 페이지로 이동가능한 이슈

- 일단 이슈만 파악했고 해결방안 논의 필요합니당

**Comment by Kimakjun** [comment]
Auth 컴포넌트에서의 페이지 라우팅 전략 
|orderStatus|OrderCallStatus|user|driver|
|------|---|----|----|
|null| null|MainPage|MainPapge|
|waiting | null |SearchingPage|해당사항 없음|
|active|approval|WatingPage|GoToOrigin|
|active|startedDrive|GoToDestination|GoToDestination|
|close|completedDriver|MainPage|MainPage|

- 기존의 order 모델에서 OrderCallStatus 추가
- close, completedDriver 상태일경우에는 운행이 종료된이후 Main 이동하므로 코드상의 구현은 필요하지 않아 보입니다.
- 혹시 다른 방법이나 빠진 사항이 있는것 같으면 피드백 부탁드릴게요. !

**Comment by cyjo9603** [comment]
`orderStatus`와 `orderCallStatus`를 합치는건 어떨까요??
`active`를 -> `approval`, `startedDrive`로 나누면 구현하기가 쉬울 것 같아요

**Comment by jongeunk0613** [comment]
말씀대로 `approval`을 두개로 나눠서 관리하는 방법이 괜찮아 보이네요!

**Comment by Kimakjun** [comment]
합치면 라우팅할때는 편할거같아요 ~! . 다만 합치게되면 현재 order 상태를 active 로 변경시키는 부분과, active 를 이용해서 조회하는 서비스로직을 조금 수정해야겠죠 ?

**Comment by hoo00nn** [comment]
채팅방 페이지도 현재 오더가 waiting이거나 active 상태일 때만 접근가능하도록 하면 더 좋을 것 같아요!

**Comment by jongeunk0613** [comment]
그렇네요! 그래도 크게 리팩토링 할 것 없이 active를 이용한 조회 서비스로직에서 조건만 적절하게 변경해주면 될 것 같은데 맞을까요?

**Comment by Kimakjun** [comment]
넵 ㅎㅎ active 로 조회했던 부분들을 approval로 바꿔주면 될 것 같아요 ! 
채팅방은 auth 컴포넌트의 두번째 인자인 UserType 에 ChatUser 같은 타입을 추가해줘서 위 상태조건에 따른 라우팅에 걸리지않으면  원래 가려던 컴포넌트(Chat) 으로 보내주면될거같아요
