### ISSUE TITLE
이미지 업로드, 저장 구현(AWS S3)

### ISSUE THREAD

**Issue by Kimakjun** [boostcamp-2020/Project09-A-Uber#149]

**Comment by cyjo9603** [comment]
Q. Naver Cloud Platform의 Object storage를 사용하지 않고 AWS의 S3를 따로 사용하시는 이유가 있으신가용??

**Comment by Kimakjun** [comment]
아 따로 사용한 이유는 없고 위 기능이 저희 프로젝트에 별로 중요하지않은 기능이기 때문에 
전에 사용해봤던 AWS S3 를 이용해서 최대한 빨리 구현하려고 했습니다 ~!.
