### ISSUE TITLE
서버에서 에러 메세지 관리 방법

### ISSUE THREAD

**Issue by hoo00nn** [boostcamp-2020/Project09-A-Uber#15]
서버에서 에러 메세지를 보낼 때 파일마다 에러메세지를 상수로 지정해두고 사용하는 방법과 따로 모듈로 에러 메세지들을 모아서 관리하는 방법 중에 어떤 방식이 더 좋은지 의견 부탁드립니다!

### 저번 미션에서 제가 했던 방식
![image](https://user-images.githubusercontent.com/52775389/99932128-7a008500-2d9a-11eb-97e2-a0def73f4688.png)

### 결론
서버 메세지를 관리하는 파일을 모듈로 만들어서 한 파일에서 모두 관리하도록 결정!

**Comment by jongeunk0613** [comment]
같은 에러 메시지를 여러 파일에서 사용하는 경우가 있을 것 같아 두번 째 방법이 좋을것 같습니다!
