### ISSUE TITLE
드라이버 탑승지 가까워졌을때 알람푸쉬기능

### ISSUE THREAD

**Issue by Kimakjun** [boostcamp-2020/Project09-A-Uber#78]
1. 드라이버 현재위치 mutaion 으로 지속적 업데이트
     드라이버현재위치 업데이트시 현재 open 되어있는 자신의 오더의 목적지와 자신의 위치가 특정거리 이내이면 subscription publish

2. 사용자는 자신의 order 쿼리 조회중에 document 에 해당 subscription 등록,  updateQuery 에서 subscription 반환데이터로 알람푸쉬띄우기

Q. Query 에 updateQuery 는 현재조회중인 query에 데이터변화가일어났을때만 실행이되나요? 

다른좋은 방법있으면 피드백 부탁드릴게요!

**Comment by cyjo9603** [comment]
흠.... query에 updateQuery를 등록하는 것 보다는 바로 useSubscription을 통해 데이터를 가져오는 건 어떨까요??

**Comment by Kimakjun** [comment]
아 useSubscription 이 있군요! useQuery 로만 불러와지는 줄 알고있었어요 감사합니다! ㅎㅎ

**Comment by hoo00nn** [comment]
제가 글이 이해가 잘 안되서 댓글로 조금만 더 설명해주시면 감사하겠습니다! ㅎㅎ

제가 생각한 방법은
1. 사용자가 출발지, 목적지를 선택 후 드라이버를 호출 후 오더매칭 (출발지, 목적지는 redux로 전역 상태관리)
2. 드라이버의 현재 위치를 subscription으로 구독한다. (드라이버 현재 위치가 Mutation으로 업데이트 될 때 마다 클라이언트는 업데이트된 데이터를 받게됨)
3. 업데이트 된 데이터(드라이버의 현재 위치정보) 와 출발지(redux 전역 상태관리중) 좌표를 비교
4. 비교  후 특정 좌표 범위내에 들어왔을 경우 사용자에게 알림 푸쉬

저는 이러한 방식으로 생각해보았습니다!

**Comment by jongeunk0613** [comment]
@hoo00nn 혹시 말씀하신 비교는 클라이언트에서 진행되는 건가요 아니면 서버에서 진행되는 것으로 생각하신건가요?

**Comment by hoo00nn** [comment]
저는 클라이언트 쪽에서 진행하는걸로 생각했습니다!

**Comment by Kimakjun** [comment]
@hoo00nn 제가설명이 부족했지만..ㅋㅋ 비슷하게 생각한거같아요 !  수도코드 형식으로 덧붙히자면 이렇게 생각하고있어요!
```
// SERVER

    1. subcription
    // driverLocation
    // pubsub.asyncIterator("UPDATE_DIRVER_LOCATION") // 드라이버의 위치정보 갱신을 구독하는 서브스크립션

    2. Mutation // 위치정보 갱신

    // if(type driver && driverOrder.status === active) // 타입 드라이버, 현재 자신의 order 가 active 이면
    // pubsub.publish("UPDATE_DIRVER_LOCATION", {driverLocation}); // 현재 드라이버 위치정보 갱신.

    // if(type User)
        return location 혹은 결과값


// CLIENT 

// {data} = useSubscription('driverLocation'); // 드라이버의 위치정보받음 지속적으로
// data 의 드라이버 정보와, order 의 출발지가 어느정도 가까워지면 사용자에게 알람푸쉬


```

**Comment by hoo00nn** [comment]
@Kimakjun 제가 이해한 바로는 order가 매칭되면 active가 close된다고 생각을 했는데 학준님은 오더가 매칭되었을 때 active가 된다고 생각하신게 맞을까요???

**Comment by Kimakjun** [comment]
@hoo00nn 아 그건 잘못적었습니다! ㅋㅋㅋ close 죠!

**Comment by Kimakjun** [comment]
음근데 그러면 이미 매칭이 성사돼서 끝난, close 된 order 들도 많으니까 현재 진행중인 매칭을 나타내는 중간상태가 필요하지 않을까요?

**Comment by hoo00nn** [comment]
@Kimakjun  저도 그래서 active, matching, close 세 가지로 두면 좀 더 괜찮을 거 같다는 생각이 들어요!
