### ISSUE TITLE
드라이버 페이지 분리

### ISSUE THREAD

**Issue by jongeunk0613** [boostcamp-2020/Project09-A-Uber#98]
드라이버의 페이지를 
1. 승인되지 않은 오더를 확인할 수 있는 페이지 &rarr; main page
2. 출발지까지 가는 경로를 표시해주는 페이지
3. 출발지에서 목적지까지 가는 경로를 표시해주는 페이지  

이렇게 의미상으로 구분해서 구현하려고 했는데 코드가 조금 복잡해 지더라도 한번에 하는게 좋을까요?
의견 부탁드립니다!

**Comment by cyjo9603** [comment]
저는 진짜 개인적인 취향으로 나누는게 좋아보이긴 합니다 (진짜 취향입니다 ㅋㅋㅋ)
페이지 하나에 다 넣어 놓는다고 해도 막 엄청 복잡해질것 같지는 않긴 한데 그래도 분리하면 확 깔끔해 보이긴 하니까요.
다른분들 의견도 들어보고 싶네요.

**Comment by Kimakjun** [comment]
저도 나누는게 좋다고 생각해요~! 지도밑 부분은 서로다른역활을하니까 분리되면 깔금할것같아요.!

**Comment by hoo00nn** [comment]
저도 나누는게 좋다고 생각해요 ㅎㅎ

**Comment by jongeunk0613** [comment]
넵!! 그럼 그렇게 진행하겠습니다 :)
